feat: CommunicationReports route and timeformate function at utils
AcademyRethink/backend-jedi-order pull request #1
Opened 2023-06-26 18:54 UTC by arnonirethink

2023-06-26 22:27 UTC, leticiavargas reviewed
Fiquei com algumas dúvidas referentes a tabela criada ... alguns relacionamentos ficaram faltando, era essa a ideia mesmo?

2023-06-26 22:27 UTC, leticiavargas commented on src/database/20230625215033_create_communication_report.ts
> +    table.integer("created_by_id");
Seria o id de quem criou a comunicação? Não entendi essa coluna

2023-06-26 22:27 UTC, leticiavargas commented on src/database/20230625215033_create_communication_report.ts
> +    table.integer("driver_id");
O driver id não precisaria de uma relação com tabela de drivers?

2023-06-26 22:27 UTC, leticiavargas commented on src/database/20230625215033_create_communication_report.ts
> +    table.integer("locomotive_id");
Não precisaria de uma relação com a tabela de locomotiva?

2023-06-26 22:27 UTC, leticiavargas commented on src/routes/communicationReportRoutes.ts
> +/* //Testando o repositório com console.log
cuidado esses códigos comentados ... ai ai ai

2023-06-26 23:36 UTC, arnonirethink commented on src/database/20230625215033_create_communication_report.ts
> +    table.integer("created_by_id");
isso mesmo, leka! :D

2023-06-26 23:37 UTC, arnonirethink commented on src/database/20230625215033_create_communication_report.ts
> +    table.integer("driver_id");
Sim, no momento como ainda não existe a tabela de driver nem de locomotiva, nem de usuario, deixei sem relação. Mas haverá uma task para fazer essa integração

2023-06-26 23:38 UTC, arnonirethink commented on src/database/20230625215033_create_communication_report.ts
> +    table.integer("locomotive_id");
Sim, no momento como ainda não existe a tabela de driver nem de locomotiva, nem de usuario, deixei sem relação. Mas haverá uma task para fazer essa integração² kkk

2023-06-26 23:39 UTC, arnonirethink commented on src/routes/communicationReportRoutes.ts
> +/* //Testando o repositório com console.log
Esse comentário eu achei legal deixar pq foi uma forma de descobrir pq minha rota estava dando erro kk pensei em reaproveitar nas próximas rotas. Daí testei via console.log o controller, o service e o repository. Mas acha melhor tirar? :)

2023-06-27 16:26 UTC, andrepfonseca requested changes

2023-06-27 16:26 UTC, andrepfonseca commented on src/routes/communicationReportRoutes.ts
> +/* //Testando o repositório com console.log
Recomendo remover estes comentários para mantermos os limpos.

2023-06-27 16:27 UTC, andrepfonseca requested changes
Você fez um PR pra mergear com a main, e não com a branch "dev".

2023-06-27 16:34 UTC, arnonirethink commented on src/routes/communicationReportRoutes.ts
> +/* //Testando o repositório com console.log
Arrasou, vou editar agora e fazer um novo pull

2023-06-29 12:37 UTC, closed without merging