tabela criada
AcademyRethink/backend-jedi-order pull request #3
Opened 2023-06-26 19:44 UTC by Juh-Sartori

tabela de locomotiva feita

2023-06-26 22:29 UTC, leticiavargas reviewed
Dá uma olhada no que está dando conflito essa teu PR.

2023-06-26 22:29 UTC, leticiavargas commented on src/database/20230622215327_create_table_locomotive.ts
> +    table.string("trainDriver");
Talvez aqui no contexto em que vocês estão não seja necessário .. mas em um mundo real, seria interessante esse trainDriver ser apenas um id que se relaciona com uma tabela com as informações do trainDriver :d

2023-06-27 16:32 UTC, andrepfonseca requested changes

2023-06-27 16:32 UTC, andrepfonseca commented on src/database/20230622215327_create_table_locomotive.ts
> +    table.string("trainDriver");
O que acha de seguirmos a sugestão da Leka e criarmos o campo driver_id como uma FK para a tabela de Driver que criaremos?
```suggestion
    // TODO- ADD FK AFTER TABLE IS CREATED
    table.integer("driver_id");
```

2023-07-03 16:08 UTC, closed without merging